###################################################################

# Created by write_sdc on Tue Nov 10 15:23:44 2020

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports {DOUT1[10]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[9]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[8]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[0]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[10]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[9]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[8]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[0]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[10]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[9]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[8]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT3[0]}]
set_load -pin_load 3.40189 [get_ports VOUT]
create_clock [get_ports CLK]  -name MY_CLK  -period 5.021  -waveform {0 2.5105}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports RST_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports VIN]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[120]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[119]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[118]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[117]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[116]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[115]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[114]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[113]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[112]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[111]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[110]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[109]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[108]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[107]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[106]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[105]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[104]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[103]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[102]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[101]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[100]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[99]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[98]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[97]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[96]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[95]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[94]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[93]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[92]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[91]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[90]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[89]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[88]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[87]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[86]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[85]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[84]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[83]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[82]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[81]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[80]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[79]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[78]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[77]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[76]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[75]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[74]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[73]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[72]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[71]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[70]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[69]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[68]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[67]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[66]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[65]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[64]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[63]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[62]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[61]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[60]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[59]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[58]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[57]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[56]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[55]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[54]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[53]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[52]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[51]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[50]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[49]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[48]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[47]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[46]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[45]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[44]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[43]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[42]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[41]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[40]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[39]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[38]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[37]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[36]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[35]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[34]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[33]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[32]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {b[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN3[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT3[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports VOUT]
