analyze -f vhdl -lib WORK ../src/common/mypackage.vhd
analyze -f vhdl -lib WORK ../src/common/reg.vhd
analyze -f vhdl -lib WORK ../src/common/packfp.vhd
analyze -f vhdl -lib WORK ../src/common/fpnormalize.vhd
analyze -f vhdl -lib WORK ../src/common/fpround.vhd
analyze -f vhdl -lib WORK ../src/common/unpackfp.vhd
analyze -f vhdl -lib WORK ../src/multiplier/fpmul_stage1_struct.vhd
analyze -f vhdl -lib WORK ../src/multiplier/fpmul_stage2_struct.vhd
analyze -f vhdl -lib WORK ../src/multiplier/fpmul_stage3_struct.vhd
analyze -f vhdl -lib WORK ../src/multiplier/fpmul_stage4_struct.vhd
analyze -f vhdl -lib WORK ../src/multiplier/fpmul_pipeline.vhd
