analyze -f vhdl -lib WORK ../src/common/mypackage.vhd
analyze -f vhdl -lib WORK ../src/common/reg.vhd
analyze -f vhdl -lib WORK ../src/common/packfp.vhd
analyze -f vhdl -lib WORK ../src/common/fpnormalize.vhd
analyze -f vhdl -lib WORK ../src/common/fpround.vhd
analyze -f vhdl -lib WORK ../src/common/unpackfp.vhd
analyze -f vhdl -lib WORK ../src/multiplier/mbe/HA.vhd
analyze -f vhdl -lib WORK ../src/multiplier/mbe/FA.vhd
analyze -f vhdl -lib WORK ../src/multiplier/mbe/partial_block_first.vhd
analyze -f vhdl -lib WORK ../src/multiplier/mbe/partial_block_intermediate.vhd
analyze -f vhdl -lib WORK ../src/multiplier/mbe/partial_block_secondlast.vhd
analyze -f vhdl -lib WORK ../src/multiplier/mbe/partial_block_last.vhd
analyze -f vhdl -lib WORK ../src/multiplier/mbe/dadda_pack.vhd
analyze -f vhdl -lib WORK ../src/multiplier/mbe/dadda_tree.vhd
analyze -f vhdl -lib WORK ../src/multiplier/mbe/MBE.vhd
analyze -f vhdl -lib WORK ../src/multiplier/fpmul_stage1_struct.vhd
analyze -f vhdl -lib WORK ../src/multiplier/fpmul_stage2_mbe_struct.vhd
analyze -f vhdl -lib WORK ../src/multiplier/fpmul_stage3_struct.vhd
analyze -f vhdl -lib WORK ../src/multiplier/fpmul_stage4_struct.vhd
analyze -f vhdl -lib WORK ../src/multiplier/fpmul_pipeline_mbe.vhd
