###################################################################

# Created by write_sdc on Sat Feb 20 17:58:17 2021

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports {PC[31]}]
set_load -pin_load 3.40189 [get_ports {PC[30]}]
set_load -pin_load 3.40189 [get_ports {PC[29]}]
set_load -pin_load 3.40189 [get_ports {PC[28]}]
set_load -pin_load 3.40189 [get_ports {PC[27]}]
set_load -pin_load 3.40189 [get_ports {PC[26]}]
set_load -pin_load 3.40189 [get_ports {PC[25]}]
set_load -pin_load 3.40189 [get_ports {PC[24]}]
set_load -pin_load 3.40189 [get_ports {PC[23]}]
set_load -pin_load 3.40189 [get_ports {PC[22]}]
set_load -pin_load 3.40189 [get_ports {PC[21]}]
set_load -pin_load 3.40189 [get_ports {PC[20]}]
set_load -pin_load 3.40189 [get_ports {PC[19]}]
set_load -pin_load 3.40189 [get_ports {PC[18]}]
set_load -pin_load 3.40189 [get_ports {PC[17]}]
set_load -pin_load 3.40189 [get_ports {PC[16]}]
set_load -pin_load 3.40189 [get_ports {PC[15]}]
set_load -pin_load 3.40189 [get_ports {PC[14]}]
set_load -pin_load 3.40189 [get_ports {PC[13]}]
set_load -pin_load 3.40189 [get_ports {PC[12]}]
set_load -pin_load 3.40189 [get_ports {PC[11]}]
set_load -pin_load 3.40189 [get_ports {PC[10]}]
set_load -pin_load 3.40189 [get_ports {PC[9]}]
set_load -pin_load 3.40189 [get_ports {PC[8]}]
set_load -pin_load 3.40189 [get_ports {PC[7]}]
set_load -pin_load 3.40189 [get_ports {PC[6]}]
set_load -pin_load 3.40189 [get_ports {PC[5]}]
set_load -pin_load 3.40189 [get_ports {PC[4]}]
set_load -pin_load 3.40189 [get_ports {PC[3]}]
set_load -pin_load 3.40189 [get_ports {PC[2]}]
set_load -pin_load 3.40189 [get_ports {PC[1]}]
set_load -pin_load 3.40189 [get_ports {PC[0]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[31]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[30]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[29]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[28]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[27]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[26]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[25]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[24]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[23]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[22]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[21]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[20]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[19]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[18]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[17]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[16]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[15]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[14]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[13]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[12]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[11]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[10]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[9]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[8]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[7]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[6]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[5]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[4]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[3]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[2]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[1]}]
set_load -pin_load 3.40189 [get_ports {ADDR_MEM[0]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[31]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[30]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[29]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[28]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[27]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[26]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[25]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[24]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[23]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[22]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[21]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[20]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[19]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[18]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[17]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[16]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[15]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[14]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[13]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[12]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[11]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[10]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[9]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[8]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[7]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[6]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[5]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[4]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[3]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[2]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[1]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA[0]}]
set_load -pin_load 3.40189 [get_ports MEM_WRITE]
set_load -pin_load 3.40189 [get_ports MEM_READ]
create_clock [get_ports CLK]  -name MY_CLK  -period 14  -waveform {0 7}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports RST_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {READ_DATA[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {ADDR_MEM[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports MEM_WRITE]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports MEM_READ]
